MD-16 http service
malsatin/my-university-android pull request #9
Opened 2020-05-14 11:32 UTC by malsatin

2020-05-14 21:01 UTC, WingedDoom requested changes

2020-05-14 21:01 UTC, WingedDoom commented on app/src/main/java/com/example/myuniversityclient/data/repository/main/MainServiceMock.kt
> +    override fun auth(email: String, password: String, onResult:  (Result<AuthMessage?>) -> Unit) {
Я бы выпилил тут nullable и плевался чем-то дефолтным в случае чего

2020-05-14 21:01 UTC, WingedDoom commented on app/src/main/java/com/example/myuniversityclient/data/repository/http/HttpClientService.kt
> +class HttpClientService : MainService {
Вообще, раз уж тащим рх, можно наверное отказаться от коллбеков и пусть возвращают `Observable` или `Single`?

2020-05-14 21:42 UTC, malsatin commented on app/src/main/java/com/example/myuniversityclient/data/repository/http/HttpClientService.kt
> +class HttpClientService : MainService {
не уверен, стоит ли ломать моки. Либо их придется переписывать тоже на обзерваблы

2020-05-15 07:56 UTC, WingedDoom commented on app/src/main/java/com/example/myuniversityclient/data/repository/http/HttpClientService.kt
> +class HttpClientService : MainService {
Ну их тоже, да. Но это не критично, можно и так оставить)

2020-05-15 11:14 UTC, merged